usr/bin/
usr/share/applications/
lib/systemd/system/
ukui-volume-control-applet-qt/build/ukui-volume-control-applet-qt usr/bin
ukui-volume-control-applet-qt/ukui-media-control-led/build/ukui-media-control-led usr/bin
ukui-volume-control-applet-qt/translations/*.qm usr/share/ukui-media/translations/
ukui-volume-control-applet-qt/data/img/* /usr/share/ukui-media/img
ukui-volume-control-applet-qt/data/qss/* /usr/share/ukui-media/qss
ukui-volume-control-applet-qt/data/sounds/ukui-sound.xml /usr/share/ukui-media/sounds
ukui-volume-control-applet-qt/data/sounds/index.theme /usr/share/sounds/ukui
ukui-volume-control-applet-qt/data/sounds/*.ogg /usr/share/ukui-media/sounds
ukui-volume-control-applet-qt/data/sounds/*.ogg /usr/share/sounds
scripts/detection_output_mode.sh /usr/share/ukui-media/scripts
